controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

login_check:
    path: /api/login_check
    methods: ['POST']

index:
    controller: App\Controller\FileController::index
    path: /    